// app/layout.tsx
import type { Metadata } from "next";
import { Raleway } from "@next/font/google";
import "./globals.css";
import { CartProvider } from "@/contexts/CartContext";

const raleway = Raleway({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
