// app/layout.tsx
import type { Metadata } from "next";
import { Raleway } from "@next/font/google";
import "./globals.css";
import { CartProvider } from "@/contexts/CartContext";
import { Footer } from "@/components/Footer/Footer";
import NavBar from "@/components/NavBar";

const raleway = Raleway({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className} antialiased body`}>
        <NavBar />
        <CartProvider>{children}</CartProvider>
        <Footer />
      </body>
    </html>
  );
}
